import type { WorkoutRoutine } from "@/lib/routine-storage"

export const REAL_WORKOUTS: WorkoutRoutine[] = [
  {
    id: "upper-rows-chest-arms",
    name: "Upper Body – Rows, Chest & Arms",
    description: "Upper body day focused on rows, chest, and arms.",
    exercises: [
      {
        id: "ub1-1",
        name: "Overhand row",
        type: "strength",
        targetSets: 2,
        targetReps: "6–8",
        notes: "Rest 2m",
      },
      {
        id: "ub1-2",
        name: "Incline dumbbell bench",
        type: "strength",
        targetSets: 2,
        targetReps: "6–8",
        notes: "Rest 2m",
      },
      {
        id: "ub1-3",
        name: "Rear delt cable fly",
        type: "strength",
        targetSets: 2,
        targetReps: "8–10",
        notes: "Rest 90s",
      },
      {
        id: "ub1-4",
        name: "Machine chest fly",
        type: "strength",
        targetSets: 2,
        targetReps: "6–8",
        notes: "Rest 90s",
      },
      {
        id: "ub1-5",
        name: "Tricep dip machine (plate loaded)",
        type: "strength",
        targetSets: 2,
        targetReps: "8–10",
        notes: "Rest 90s",
      },
      {
        id: "ub1-6",
        name: "Dumbbell hammer curls",
        type: "strength",
        targetSets: 2,
        targetReps: "6–8",
        notes: "Rest 90s",
      },
      {
        id: "ub1-7",
        name: "Side crunch (Roman chair)",
        type: "strength",
        targetSets: 3,
        targetReps: "8–10",
        notes: "Rest 60s",
      },
      {
        id: "ub1-8",
        name: "Decline bench knee raises",
        type: "strength",
        targetSets: 3,
        targetReps: "10",
        notes: "Rest 60s",
      },
    ],
    estimatedTime: "55–65 min",
    category: "Strength",
    createdAt: "2025-11-30T00:00:00.000Z",
    updatedAt: "2025-11-30T00:00:00.000Z",
  },
  {
    id: "upper-chest-back-shoulders",
    name: "Upper Body – Chest, Back & Shoulders",
    description: "Upper body day with chest, back, shoulders, and core supersets.",
    exercises: [
      {
        id: "ub2-1",
        name: "Upper body warmup",
        type: "other",
        targetSets: 2,
        targetReps: "10–12 each",
        notes: "Rest 90s",
      },
      {
        id: "ub2-2",
        name: "Incline Smith machine bench",
        type: "strength",
        targetSets: 2,
        targetReps: "8–10",
        notes: "Rest 2m",
      },
      {
        id: "ub2-3",
        name: "Machine chest press",
        type: "strength",
        targetSets: 2,
        targetReps: "5–8",
        notes: "Rest 2m",
      },
      {
        id: "ub2-4",
        name: "Lat pulldown",
        type: "strength",
        targetSets: 2,
        targetReps: "6–8",
        notes: "Rest 90s",
      },
      {
        id: "ub2-5",
        name: "Chest dips",
        type: "strength",
        targetSets: 2,
        targetReps: "6–8",
        notes: "Rest 90s",
      },
      {
        id: "ub2-6",
        name: "Bench supported hi–lo cable row",
        type: "strength",
        targetSets: 2,
        targetReps: "8–10",
        notes: "Rest 90s",
      },
      {
        id: "ub2-7",
        name: "Tricep double rope pushdown",
        type: "strength",
        targetSets: 3,
        targetReps: "8–10",
        notes: "Rest 90s",
      },
      {
        id: "ub2-8",
        name: "Egyptian lateral raise",
        type: "strength",
        targetSets: 3,
        targetReps: "10–12",
        notes: "Rest 90s",
      },
      {
        id: "ub2-9",
        name: "Cable crunch (superset)",
        type: "strength",
        targetSets: 3,
        targetReps: "12",
        notes: "Rest 90s",
      },
      {
        id: "ub2-10",
        name: "Hanging leg raise (superset)",
        type: "strength",
        targetSets: 3,
        targetReps: "12",
        notes: "Rest 90s",
      },
    ],
    estimatedTime: "55–65 min",
    category: "Strength",
    createdAt: "2025-11-30T00:00:00.000Z",
    updatedAt: "2025-11-30T00:00:00.000Z",
  },
  {
    id: "upper-shoulders-chest-arms",
    name: "Upper Body – Shoulders, Chest & Arms",
    description: "Upper body day with heavy shoulder focus plus chest and arms.",
    exercises: [
      {
        id: "ub3-1",
        name: "Upper body warmup",
        type: "other",
        targetSets: 2,
        targetReps: "10–12",
        notes: "Rest 90s",
      },
      {
        id: "ub3-2",
        name: "Smith machine shoulder press",
        type: "strength",
        targetSets: 3,
        targetReps: "4–6",
        notes: "Rest 2m",
      },
      {
        id: "ub3-3",
        name: "Incline machine chest press (captioned)",
        type: "strength",
        targetSets: 2,
        targetReps: "5–7",
        notes: "Rest 2m",
      },
      {
        id: "ub3-4",
        name: "Machine rear delt fly",
        type: "strength",
        targetSets: 2,
        targetReps: "7–10",
        notes: "Rest 90s",
      },
      {
        id: "ub3-5",
        name: "Cable lateral raise (with wrist strap)",
        type: "strength",
        targetSets: 2,
        targetReps: "5–7",
        notes: "Rest 90s",
      },
      {
        id: "ub3-6",
        name: "Single arm tricep pushdown (with wrist strap)",
        type: "strength",
        targetSets: 3,
        targetReps: "6–8",
        notes: "Rest 90s",
      },
      {
        id: "ub3-7",
        name: "Bayesian biceps cable curl",
        type: "strength",
        targetSets: 3,
        targetReps: "6–10",
        notes: "Rest 90s",
      },
      {
        id: "ub3-8",
        name: "Cable rotation",
        type: "strength",
        targetSets: 2,
        targetReps: "8–10",
        notes: "Rest 60s",
      },
      {
        id: "ub3-9",
        name: "Oblique cable crunch",
        type: "strength",
        targetSets: 2,
        targetReps: "10",
        notes: "Rest 60s",
      },
    ],
    estimatedTime: "55–65 min",
    category: "Strength",
    createdAt: "2025-11-30T00:00:00.000Z",
    updatedAt: "2025-11-30T00:00:00.000Z",
  },
  {
    id: "legs-quads-hams-1",
    name: "Lower Body – Quads & Hamstrings (Legs 1)",
    description: "Lower body day focusing on quads and hamstrings.",
    exercises: [
      {
        id: "lg1-1",
        name: "Leg day warmup",
        type: "other",
        targetSets: 1,
        targetReps: "3 min",
        notes: "Rest 0s",
      },
      {
        id: "lg1-2",
        name: "Hip adduction",
        type: "strength",
        targetSets: 3,
        targetReps: "12–15",
        notes: "Rest 90s",
      },
      {
        id: "lg1-3",
        name: "Pendulum squat",
        type: "strength",
        targetSets: 2,
        targetReps: "5–7",
        notes: "Rest 3m",
      },
      {
        id: "lg1-4",
        name: "Dumbbell split squat (squat rack setup)",
        type: "strength",
        targetSets: 2,
        targetReps: "8–10",
        notes: "Rest 2m",
      },
      {
        id: "lg1-5",
        name: "Leg extension",
        type: "strength",
        targetSets: 3,
        targetReps: "6–8",
        notes: "Rest 90s",
      },
      {
        id: "lg1-6",
        name: "Seated hamstring curl",
        type: "strength",
        targetSets: 3,
        targetReps: "6–8",
        notes: "Rest 90s",
      },
      {
        id: "lg1-7",
        name: "Single leg hamstring curl",
        type: "strength",
        targetSets: 2,
        targetReps: "8–10",
        notes: "Rest 90s",
      },
    ],
    estimatedTime: "50–60 min",
    category: "Strength",
    createdAt: "2025-11-30T00:00:00.000Z",
    updatedAt: "2025-11-30T00:00:00.000Z",
  },
  {
    id: "legs-glutes-hams-2",
    name: "Lower Body – Glutes & Hamstrings (Legs 2)",
    description: "Lower body day emphasizing glutes and hamstrings.",
    exercises: [
      {
        id: "lg2-1",
        name: "Leg day warmup",
        type: "other",
        targetSets: 1,
        targetReps: "3 min",
        notes: "Rest 3m",
      },
      {
        id: "lg2-2",
        name: "Seated hamstring curl",
        type: "strength",
        targetSets: 2,
        targetReps: "8–10",
        notes: "Rest 90s",
      },
      {
        id: "lg2-3",
        name: "Belt squat RDL",
        type: "strength",
        targetSets: 3,
        targetReps: "6–8",
        notes: "Rest 2m",
      },
      {
        id: "lg2-4",
        name: "Hip thrust",
        type: "strength",
        targetSets: 3,
        targetReps: "6–8",
        notes: "Rest 2m",
      },
      {
        id: "lg2-5",
        name: "Single leg RDL (bench supported)",
        type: "strength",
        targetSets: 2,
        targetReps: "8–10",
        notes: "Rest 2m",
      },
      {
        id: "lg2-6",
        name: "Glute biased extension",
        type: "strength",
        targetSets: 2,
        targetReps: "6–8",
        notes: "Rest 2m",
      },
      {
        id: "lg2-7",
        name: "Leg extension",
        type: "strength",
        targetSets: 2,
        targetReps: "8–10",
        notes: "Rest 90s",
      },
      {
        id: "lg2-8",
        name: "Machine calf raise (gastroc)",
        type: "strength",
        targetSets: 3,
        targetReps: "15–20",
        notes: "Rest 90s",
      },
      {
        id: "lg2-9",
        name: "Cable crunch",
        type: "strength",
        targetSets: 3,
        targetReps: "15–20",
        notes: "Rest 90s",
      },
    ],
    estimatedTime: "55–65 min",
    category: "Strength",
    createdAt: "2025-11-30T00:00:00.000Z",
    updatedAt: "2025-11-30T00:00:00.000Z",
  },
]
